# Homebrew Cask — ProxyOrbit
# Auto-generated by .github/workflows/update-tap.yml on every release publish.
# Template tokens: 1.0.0  4da453235ca525a47d6daf130974fa14823438b6060c5b1fc0555e9f241bd263  59b4303f730af9fe7e52e492ec407077da9dd1b76535fb7bd618169f7c214217
#
# Manual install: brew install --cask slothlabsorg/tap/proxyorbit
# Tap setup:      brew tap slothlabsorg/tap

cask "proxyorbit" do
  version "1.0.0"

  on_arm do
    url "https://github.com/slothlabsorg/proxyorbit/releases/download/v#{version}/ProxyOrbit_#{version}_aarch64.dmg"
    sha256 "4da453235ca525a47d6daf130974fa14823438b6060c5b1fc0555e9f241bd263"
  end

  on_intel do
    url "https://github.com/slothlabsorg/proxyorbit/releases/download/v#{version}/ProxyOrbit_#{version}_x64.dmg"
    sha256 "59b4303f730af9fe7e52e492ec407077da9dd1b76535fb7bd618169f7c214217"
  end

  name        "ProxyOrbit"
  desc        "HTTP/HTTPS proxy inspector — capture traffic, filter requests, set system proxy"
  homepage    "https://github.com/slothlabsorg/proxyorbit"

  app "ProxyOrbit.app"

  zap trash: [
    "~/Library/Application Support/io.slothlabs.proxyorbit",
    "~/Library/Logs/io.slothlabs.proxyorbit",
    "~/Library/Preferences/io.slothlabs.proxyorbit.plist",
    "~/Library/Saved Application State/io.slothlabs.proxyorbit.savedState",
  ]
end
