# Homebrew Cask — WattsOrbit
# Auto-generated by .github/workflows/update-tap.yml on every release publish.
# Do not edit by hand — see distribute/homebrew/wattsorbit.rb.tmpl in the source repo.
#
# Manual install: brew install --cask slothlabsorg/tap/wattsorbit
# Tap setup:      brew tap slothlabsorg/tap

cask "wattsorbit" do
  version "1.1.0"

  on_arm do
    url "https://github.com/slothlabsorg/wattsorbit/releases/download/v#{version}/WattsOrbit_#{version}_aarch64.dmg"
    sha256 "1b56cd2d481f5bea6df76a610e833e8310f9a266763de188b514e00b7da66971"
  end

  on_intel do
    url "https://github.com/slothlabsorg/wattsorbit/releases/download/v#{version}/WattsOrbit_#{version}_x64.dmg"
    sha256 "7a18aea42b6311c8026874d4066d11d5066623130026a84659393a9c4f45a638"
  end

  name        "WattsOrbit"
  desc        "Cross-platform menu-bar power monitor"
  homepage    "https://github.com/slothlabsorg/wattsorbit"

  app "WattsOrbit.app"

  zap trash: [
    "~/Library/Application Support/io.slothlabs.wattsorbit",
    "~/Library/Logs/io.slothlabs.wattsorbit",
    "~/Library/Preferences/io.slothlabs.wattsorbit.plist",
    "~/Library/Saved Application State/io.slothlabs.wattsorbit.savedState",
  ]
end
