# Homebrew Cask — WattsOrbit
# Auto-generated by .github/workflows/update-tap.yml on every release publish.
# Do not edit by hand — see distribute/homebrew/wattsorbit.rb.tmpl in the source repo.
#
# Manual install: brew install --cask slothlabsorg/tap/wattsorbit
# Tap setup:      brew tap slothlabsorg/tap

cask "wattsorbit" do
  version "1.1.1"

  on_arm do
    url "https://github.com/slothlabsorg/wattsorbit/releases/download/v#{version}/WattsOrbit_#{version}_aarch64.dmg"
    sha256 "b03040ddf5b6abf694630a7f5caf9b6b21c716e8e9ae95c18b1e4ab11565a7d4"
  end

  on_intel do
    url "https://github.com/slothlabsorg/wattsorbit/releases/download/v#{version}/WattsOrbit_#{version}_x64.dmg"
    sha256 "ec4a8fc3b42f7362fcf18069e4974037303a894739cc1a7ea75d07ffba793967"
  end

  name        "WattsOrbit"
  desc        "Cross-platform menu-bar power monitor"
  homepage    "https://github.com/slothlabsorg/wattsorbit"

  app "WattsOrbit.app"

  zap trash: [
    "~/Library/Application Support/io.slothlabs.wattsorbit",
    "~/Library/Logs/io.slothlabs.wattsorbit",
    "~/Library/Preferences/io.slothlabs.wattsorbit.plist",
    "~/Library/Saved Application State/io.slothlabs.wattsorbit.savedState",
  ]
end
