# Homebrew Cask — WattsOrbit
# Auto-generated by .github/workflows/update-tap.yml on every release publish.
# Do not edit by hand — see distribute/homebrew/wattsorbit.rb.tmpl in the source repo.
#
# Manual install: brew install --cask slothlabsorg/tap/wattsorbit
# Tap setup:      brew tap slothlabsorg/tap

cask "wattsorbit" do
  version "1.2.0"

  on_arm do
    url "https://github.com/slothlabsorg/wattsorbit/releases/download/v#{version}/WattsOrbit_#{version}_aarch64.dmg"
    sha256 "e7c3fce5c6f1e48b0eb0182f07e992f64ad24ec92532e4a56ed2055b3d38adef"
  end

  on_intel do
    url "https://github.com/slothlabsorg/wattsorbit/releases/download/v#{version}/WattsOrbit_#{version}_x64.dmg"
    sha256 "bf89622f1505b0c07f3636133035c741f33575dc73caf55b5c53c2a5262c44f7"
  end

  name        "WattsOrbit"
  desc        "Cross-platform menu-bar power monitor"
  homepage    "https://github.com/slothlabsorg/wattsorbit"

  app "WattsOrbit.app"

  zap trash: [
    "~/Library/Application Support/io.slothlabs.wattsorbit",
    "~/Library/Logs/io.slothlabs.wattsorbit",
    "~/Library/Preferences/io.slothlabs.wattsorbit.plist",
    "~/Library/Saved Application State/io.slothlabs.wattsorbit.savedState",
  ]
end
